# テーマ1 Python基礎演習

## 副題
Notebook の使い方と、データ分析に入る前の Python 準備

## 対象
Python を初めて学ぶ大学1年生を想定

## この回の位置づけ
この回ではグラフは扱いません。可視化はテーマ2でまとめて扱います。
まずは Python を書いて実行し、結果を見て、少し直して、また動かすことに慣れます。
NumPy の配列・行列も最後に少しだけ触れます。

## 到達目標
- Notebook 上でセルを実行し、結果を確認しながら試行錯誤できる
- 加減乗除、変数、`print`、文字列、リスト、条件分岐、繰り返し、関数の基本を使える
- NumPy 配列の形と簡単な集計を確認できる
- 次回以降で使う Iris データを読み込み、表として中身を確認できる

## 今日の成果物
- 数値や文字列を使った簡単な Python コードを自分で書き換えて実行する
- 関数を1つ使って計算結果を確認する
- NumPy の2次元配列の行数・列数・平均を確認する
- Iris データの先頭行と列名を確認する

## 進め方
- 上から順にセルを実行してください
- `TODO` の部分を少しずつ書き換えながら進めてください
- わからないところは、まず実行結果を見てから前のセルに戻って確認してください

## この回で大切にする考え方

Python の文法を最初から全部覚える必要はありません。この授業では、次の小さなサイクルを何度も回します。

1. コードを実行する
2. 結果を見る
3. 予想と違うところを直す
4. 結果を自分の言葉で説明する

Notebook は、このサイクルを短く回すための道具です。セルを実行したら、出力を必ず見て「何が起きたか」を確認してください。


### うまく動かないときの見方

エラーが出たときは、まず最後の1行に注目してください。Python のエラーは長く見えますが、多くの場合、最後の行に「何が問題だったか」が短く書かれています。

よくある例:

- `NameError`: 変数名をまだ作っていない、またはスペルが違う
- `SyntaxError`: `:` や `)` など、書き方の記号が足りない
- `IndentationError`: `if` や `for` の中の字下げがずれている

エラーは失敗ではなく、コンピュータからのヒントです。直したら同じセルをもう一度実行してください。


### Step 0: 加減乗除の確認
まずは Python の基本演算子がそのまま使えることを確認します。セルを実行すると、計算式と結果が表示されます。

#### 解説: Python の計算

Python では、数式に近い形で計算を書けます。

- `+`: 足し算
- `-`: 引き算
- `*`: 掛け算
- `/`: 割り算
- `**`: べき乗

例えば、長方形の面積は次のように考えられます。

$$
面積 = 横幅 \times 高さ
$$

コードでは `width * height` のように書きます。


In [22]:
# ===== Step 0: 加減乗除 =====
# TODO: まずはセルを実行して、計算結果が下に表示されることを確認する
print('1 + 2 =', 1 + 2)
print('5 - 3 =', 5 - 3)
print('4 * 6 =', 4 * 6)
print('8 / 2 =', 8 / 2)

# ヒント: +, -, *, / はそれぞれ足し算、引き算、掛け算、割り算です

1 + 2 = 3
5 - 3 = 2
4 * 6 = 24
8 / 2 = 4.0


In [23]:
# ===== 追加演習: 面積を計算する =====
# TODO: width と height の値を変えて、面積がどう変わるか確認する
width = 3
height = 5
area = width * height

print('横幅 =', width)
print('高さ =', height)
print('面積 =', area)


横幅 = 3
高さ = 5
面積 = 15


### Step 1: 変数を使って計算する
値を変数に入れてから、変数同士の計算を確認します。数字を変えると結果も変わるので、セルを少し書き換えて試してください.

In [24]:
# ===== Step 1: 変数 =====
# TODO: 数字を入れ替えて、結果がどう変わるか確認する
a = 10
b = 4

print('a =', a)
print('b =', b)
print('a + b =', a + b)
print('a - b =', a - b)
print('a * b =', a * b)
print('a / b =', a / b)

# ヒント: = は値を変数に入れる記号です

a = 10
b = 4
a + b = 14
a - b = 6
a * b = 40
a / b = 2.5


### Step 2: 文字列・リスト・条件分岐・繰り返し

数値の計算だけでなく、文字や複数の値も扱ってみます。

Python では、
- 文字列: `'Iris'` のように書く
- リスト: `['a', 'b', 'c']` のように複数の値を並べる
- 条件分岐: `if` を使って条件で処理を分ける
- 繰り返し: `for` を使って要素を1つずつ取り出す

ここでは「読みながら動かす」ことを重視してください。

In [25]:
# ===== Step 2-1: 文字列とリスト =====
name = 'Iris'
unit = 'cm'

print('データ名:', name)
print('単位:', unit)

features = ['sepal length', 'sepal width', 'petal length', 'petal width']
print('特徴量一覧:', features)
print('特徴量の数:', len(features))
print('最初の特徴量:', features[0])

# TODO: 下の1行を完成させて、最後の特徴量を表示する
print('最後の特徴量:', features[-1])

# TODO: append を使って 'species' を追加してみる
features.append('species')
print('追加後の特徴量一覧:', features)

データ名: Iris
単位: cm
特徴量一覧: ['sepal length', 'sepal width', 'petal length', 'petal width']
特徴量の数: 4
最初の特徴量: sepal length
最後の特徴量: petal width
追加後の特徴量一覧: ['sepal length', 'sepal width', 'petal length', 'petal width', 'species']


In [26]:
# ===== Step 2-2: 条件分岐 =====
score = 75
threshold = 60

print('score =', score)
print('threshold =', threshold)

if score >= threshold:
    print(score, 'は基準値', threshold, '以上です')
else:
    print(score, 'は基準値', threshold, '未満です')

# TODO: score または threshold を変えて、表示がどう変わるか確認する

score = 75
threshold = 60
75 は基準値 60 以上です


In [27]:
# ===== Step 2-3: for ループ =====
fruits = ['apple', 'banana', 'cherry']

for index, fruit in enumerate(fruits):
    print(index, ':', fruit)

# TODO: fruits の中身を変えて、ループの動きを確認する

0 : apple
1 : banana
2 : cherry


### Step 3: 関数を作る

同じ計算を何度も使いたいときは、関数にまとめると便利です。

関数では、
- 入力: 関数に渡す値
- 出力: 関数が返す値

まずは長方形の面積を求める関数を読んで、入力を変えて試してください。

In [28]:
# ===== Step 3: 関数 =====
def rectangle_area(width, height):
    return width * height

print('3 x 5 の面積 =', rectangle_area(3, 5))
print('7 x 2 の面積 =', rectangle_area(7, 2))

# TODO: 引数を変えて、面積がどう変わるか確認する

3 x 5 の面積 = 15
7 x 2 の面積 = 14


### Step 4: NumPy で配列と行列を扱う

データ分析では、数値が並んだ配列をまとめて扱うことが多くあります。

`NumPy` は、そのための基本ライブラリです。ここでは 2 次元配列を「行と列を持つ表に近いもの」として見ます。

この段階では、
- 形を確認する
- 行ごと、列ごとに平均を出す

ところまでできれば十分です。

In [29]:
# ===== Step 4: NumPy 配列 =====
import numpy as np

scores = np.array([
    [80, 65, 70],
    [90, 88, 92],
    [75, 60, 78]
])

print('scores =')
print(scores)
print('形 =', scores.shape)
print('各行の平均 =', scores.mean(axis=1))
print('各列の平均 =', scores.mean(axis=0))

# TODO: 1つ値を変えて、平均がどう変わるか確認する

scores =
[[80 65 70]
 [90 88 92]
 [75 60 78]]
形 = (3, 3)
各行の平均 = [71.66666667 90.         71.        ]
各列の平均 = [81.66666667 71.         80.        ]


### Step 5: ライブラリを読み込んでデータを準備する

ここからは、次回以降の分析で使う表形式データに少し触れます。

ただし、この回の中心は Python の基本操作です。グラフはまだ描きません。

`pandas` は表を扱うためのライブラリ、`load_iris` は練習用データを読み込むための関数です。

#### 解説: 表形式データと DataFrame

Iris データセットは、花の特徴を行と列で表した表形式データです。

- 1行: 1つの花の観測データ
- 1列: 花びらの長さ、がく片の幅などの特徴量
- `species`: 花の種類

データ分析では、まず次を確認します。

- 行数と列数
- 列名
- 先頭数行
- 値の範囲や平均

これは「モデルを作る前に、データが何を表しているかを理解する」ためです。


In [ ]:
# ===== Step 5: ライブラリ読み込みとデータ準備 =====
import pandas as pd
from sklearn.datasets import load_iris

# TODO: Irisデータセットを読み込む
iris = load_iris(as_frame=True)
df = iris.frame.copy()
df['species'] = df['target'].map(dict(enumerate(iris.target_names)))

print('行数, 列数 =', df.shape)
display(df.head())

# ヒント: DataFrame は表のようにデータを扱うための型です


### Step 6: データを確認する

列名、基本統計量、件数を確認します。

この回では「表として何が入っているか」を確認するところまでに留めます。

分布や関係をグラフで見る作業はテーマ2で行います。

In [ ]:
# ===== Step 6: データ確認 =====
# TODO: 先頭5行、列名、基本統計量を確認する
print('列名一覧')
print(df.columns.tolist())
print('\n基本統計量')
display(df.describe())

print('\n品種ごとの件数')
display(df['species'].value_counts())

# ヒント: `df['列名']` で1つの列を取り出せます
#       df.describe() で各列の平均、標準偏差、最小値、最大値などが確認できます


#### ミニ演習: データから1文で説明する

下の文を自分の観察に合わせて書き換えてください。

正解を探すよりも、「どの出力を根拠にそう言ったのか」を意識して説明することが大切です。

例
- 基本統計量から、`________` の平均は `________` あたりだとわかる。
- 品種ごとの件数を見ると、`________` が `________` 件ある。
- 列名から、このデータは `________` に関する表だと考えられる。

## 振り返り
- 加減乗除と変数のどこで意味が分かりにくかったですか。
- 文字列・リスト・条件分岐・繰り返しのどの部分が新しく感じましたか。
- 関数は「何を入力して、何を返すもの」だと理解しましたか。
- NumPy の2次元配列では、行と列をどう読むと理解しやすかったですか。
- Iris データにはどのような列があり、それぞれ何を表していそうですか。
- 次回の可視化で確かめてみたいことを1つ書いてください。

## 演習課題

以下の演習をノートブック上で実行し、結果を確認してください。

### 演習1: 基本計算と変数 (簡単)

1. 変数 `age` に自分の年齢（または好きな数字）を代入し、それを2倍した値を表示してください。
2. 変数 `price` に 1500 を代入し、8%の消費税を加えた合計金額を計算して表示してください。

```python
# ここにコードを書いてください
age = 
print("2倍:", )

price = 1500
tax_rate = 0.08
total = 
print("税込価格:", total)
```

### 演習2: リストと条件分岐 (簡単)

1. 変数 `scores` に `[75, 88, 62, 95, 43]` を代入してください。
2. このリストの各要素について、60以上なら「合格」、それ以下なら「不合格」と表示するコードを書いてください。

```python
# ここにコードを書いてください
scores = [75, 88, 62, 95, 43]
for score in scores:
    if :
        print(f"{score}点 → ")
    else:
        print(f"{score}点 → ")
```

### 演習3: Irisデータ確認 (簡単)

1. `iris` データセットの列名を再度確認し、それぞれの列が何を表しているか1行ずつ書いてください。
2. `df.describe()` の結果から、`sepal length (cm)` の最大値と最小値を読み取り、その差（範囲）を計算してください。

```python
# ここにコードを書いてください
print("列名:", )

desc = df.describe()
sepal_max = desc.loc['max', 'sepal length (cm)']
sepal_min = desc.loc['min', 'sepal length (cm)']
print(f"sepal length (cm) の範囲: {sepal_max - sepal_min}")
```

---

## レポート課題

以下のレポートを提出してください（A4 1ページ程度、またはノートブックのセルに記述）。

### レポート項目

1. **Pythonの基本操作** (200字程度)
   - 変数・リスト・条件分岐・繰り返しの中で、最も新しく感じた概念はどれですか。その理由を説明してください。

2. **NumPy配列** (200字程度)
   - 1次元配列と2次元配列の違いを、自分の言葉で説明してください。また、2次元配列の「行」と「列」はどのように区別しましたか。

3. **Irisデータセット** (200字程度)
   - Irisデータにはどのような列がありますか。それぞれの列が何を表しているか、そしてこのデータを使って何ができるかを説明してください。

4. **次回への期待** (100字程度)
   - 次回の「データ可視化」で、特に確認してみたいことは何ですか。

